# Copyright 2020 NephoSolutions SRL, Sebastian Trebitz
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Include OS dependent variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"

- name: Include OS dependent tasks
  include: "{{ ansible_os_family }}.yaml"

- name: Ensure sshguard service is started and enabled on boot
  service:
    name: "{{ sshguard_service }}"
    state: "{{ sshguard_service_state }}"
    enabled: "{{ sshguard_service_enabled }}"
  when: not molecule | default(false)

- name: Configure sshguard and whitelist from templates
  template:
    src: "sshguard/{{ item }}.j2"
    dest: "{{ sshguard_config_path }}/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ sshguard_config_items }}"
  notify: restart sshguard service
