# Copyright 2020 NephoSolutions SRL, Sebastian Trebitz
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: geerlingguy/docker-centos7-ansible
    image_version: latest
    pre_build_image: true
    privileged: true
    volume_mounts:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /usr/sbin/init
    environment: { container: docker }
  - name: centos8
    image: geerlingguy/docker-centos8-ansible
    image_version: latest
    pre_build_image: true
    privileged: true
    volume_mounts:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /usr/sbin/init
    environment: { container: docker }
  - name: debian9
    image: geerlingguy/docker-debian9-ansible
    image_version: latest
    pre_build_image: true
    privileged: true
    volume_mounts:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    environment: { container: docker }
  - name: debian10
    image: geerlingguy/docker-debian10-ansible
    image_version: latest
    pre_build_image: true
    privileged: true
    volume_mounts:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    environment: { container: docker }
  - name: ubuntu1604
    image: geerlingguy/docker-ubuntu1604-ansible
    image_version: latest
    pre_build_image: true
    privileged: true
    volume_mounts:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    environment: { container: docker }
  - name: ubuntu1804
    image: geerlingguy/docker-ubuntu1804-ansible
    image_version: latest
    pre_build_image: true
    privileged: true
    volume_mounts:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    environment: { container: docker }
provisioner:
  name: ansible
  inventory:
    host_vars:
      centos8:
        ansible_python_interpreter: /usr/bin/python3
      debian10:
        ansible_python_interpreter: /usr/bin/python3
      ubuntu1804:
        ansible_python_interpreter: /usr/bin/python3
  log: true
